---
name: Push
on: push

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        name: Run StyLua
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.18.1
          args: --check .
